apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fraud-platform-eks
  region: ap-south-1
  version: "1.34"

vpc:
  id: <VPC_ID>
  subnets:
    private:
      ap-south-1a:
        id: <PRIVATE_SUBNET_1A_ID>
      ap-south-1b:
        id: <PRIVATE_SUBNET_1B_ID>

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
  accessEntries:
    - principalARN: <GITHUB_ACTIONS_ROLE_ARN>
      type: STANDARD
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster

managedNodeGroups:
  - name: fraud-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    privateNetworking: true
