apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-engine
  namespace: fraud-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-engine
  template:
    metadata:
      labels:
        app: fraud-engine
    spec:
      containers:
        - name: fraud-engine
          image: fraud-engine:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_HOST
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_NAME
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "transactions"
            - name: KAFKA_GROUP_ID
              value: "fraud-engine"