apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-engine
  template:
    metadata:
      labels:
        app: fraud-engine
    spec:
      containers:
        - name: fraud-engine
          image: 649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-engine:latest
          imagePullPolicy: Always
