name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install API dependencies
        run: |
          pip install -r transaction-api/requirements.txt

      - name: Verify AWS access
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
            docker login \
            --username AWS \
            --password-stdin \
            649320110694.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build API Docker image
        run: |
          docker build \
            -t 649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-api:${{ github.sha }} \
            ./transaction-api

      - name: Build Fraud Engine Docker image
        run: |
          docker build \
            -t 649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-engine:${{ github.sha }} \
            ./fraud-engine

      - name: Push API image to ECR
        run: |
          docker push \
            649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-api:${{ github.sha }}

      - name: Push Fraud Engine image to ECR
        run: |
          docker push \
            649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-engine:${{ github.sha }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name fraud-platform-eks

          kubectl get nodes

      - name: Deploy images to EKS
        run: |
          kubectl -n fraud-platform set image deployment/transaction-api \
            transaction-api=649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-api:${{ github.sha }}

          kubectl -n fraud-platform set image deployment/fraud-engine \
            fraud-engine=649320110694.dkr.ecr.ap-south-1.amazonaws.com/fraud-engine:${{ github.sha }}

          kubectl -n fraud-platform rollout status deployment/transaction-api

          kubectl -n fraud-platform rollout status deployment/fraud-engine

      - name: Verify EKS deployment
        run: |
          kubectl -n fraud-platform get deployments
          kubectl -n fraud-platform get pods

